name: pet_life
description: "Pet Life - diario intelligente e organizzatore per la cura del pet."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^20.1.0
  flutter_riverpod: ^2.6.1
  flutter_timezone: ^5.0.2
  go_router: ^14.8.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true